site_name: Agents SDK Models
site_description: OpenAI Agents SDKを拡張するモデルアダプター＆ワークフロー集
site_author: kitfactory
repo_url: https://github.com/kitfactory/agents-sdk-models
repo_name: kitfactory/agents-sdk-models

theme:
  name: material
  language: ja

nav:
  - はじめに: index.md
  - APIリファレンス: api_reference.md
  - チュートリアル:
      - クイックスタート: tutorials/quickstart.md
      - 応用例: tutorials/advanced.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true 