site_name: Agents SDK Models
site_description: OpenAI Agents SDKを拡張するモデルアダプター＆ワークフロー集
site_author: kitfactory
repo_url: https://github.com/kitfactory/agents-sdk-models
repo_name: kitfactory/agents-sdk-models

theme:
  name: material
  language: ja
  features:
    - mermaid

plugins:
  - search

nav:
  - はじめに: index.md
  - APIリファレンス: api_reference.md
  - チュートリアル:
      - クイックスタート: tutorials/quickstart.md
      - 応用例: tutorials/advanced.md

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed
  - admonition
  - codehilite
  - toc:
      permalink: true

# mermaid.js for client-side rendering
extra_javascript:
  - https://unpkg.com/mermaid@10.4.0/dist/mermaid.min.js 